# Generated by Django 2.2.1 on 2019-08-12 21:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='user',
            field=models.ForeignKey(default=0, on_delete='models.CASCADE', to=settings.AUTH_USER_MODEL),
        ),
    ]
