# Generated by Django 2.2.1 on 2019-08-12 22:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0007_auto_20190812_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='user',
            field=models.ForeignKey(default='1', on_delete='models.CASCADE', to=settings.AUTH_USER_MODEL),
        ),
    ]
